# Generated by Django 4.1.4 on 2022-12-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('content', models.TextField(verbose_name='متن کامنت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_module.blogpost', verbose_name='پست هدف')),
            ],
        ),
    ]
