# Generated by Django 4.1.4 on 2022-12-12 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0002_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='تائید'),
        ),
    ]
