# Generated by Django 4.1.4 on 2022-12-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0003_postcomment_date_postcomment_is_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
