# Generated by Django 4.1.4 on 2022-12-31 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='uploads/image/courses', verbose_name='تصویر')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('level', models.CharField(choices=[('A', 'مقدماتی'), ('B', 'متوسط'), ('C', 'پیشرفته')], max_length=15, verbose_name='سطح')),
                ('is_show', models.BooleanField(verbose_name='نمایش')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
        ),
    ]
