# Generated by Django 4.1.4 on 2022-12-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='slug',
            field=models.SlugField(default='x', unique=True, verbose_name='آدرس'),
        ),
    ]
