# Generated by Django 4.1.4 on 2022-12-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0002_coursemodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='image',
            field=models.ImageField(upload_to='image/courses', verbose_name='تصویر'),
        ),
    ]
