# Generated by Django 4.1.4 on 2022-12-31 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0003_alter_coursemodel_options_alter_coursemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_module.coursemodel', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل ها',
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('short_description', models.CharField(max_length=200, verbose_name='توضیح کوتاه')),
                ('video', models.FileField(upload_to='videos/courses', verbose_name='ویدیو')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_module.courseseason', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها',
            },
        ),
    ]
